services:
  app:
    build: .
    container_name: roomify-app
    env_file:
      - src/.env
    # tidak ada volumes yang menimpa /var/www/html
    networks:
      - roomify

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - roomify

networks:
  roomify:
