apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomify-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roomify
  template:
    metadata:
      labels:
        app: roomify
    spec:
      containers:
        # --- APP CONTAINER (PHP) ---
        - name: php-backend
          image: diwamln/roomify:latest # Akan diganti Jenkins
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          # INI BAGIAN PENTING: Inject ENV dari Secret
          envFrom:
            - secretRef:
                name: roomify-secrets
          volumeMounts:
            - name: shared-assets
              mountPath: /shared-public
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -a /var/www/html/public/. /shared-public/"]

        # --- WEB SERVER (NGINX) ---
        - name: nginx-server
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-assets
              mountPath: /var/www/html/public

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: shared-assets
          emptyDir: {}
