apiVersion: v1
kind: Service
metadata:
  name: roomify-db
spec:
  ports:
    - port: 5432
  selector:
    app: roomify-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomify-db
spec:
  selector:
    matchLabels:
      app: roomify-db
  template:
    metadata:
      labels:
        app: roomify-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            # Mengambil user/pass/db name dari Secret yang kita buat di atas
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: roomify-secrets
                  key: DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: roomify-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roomify-secrets
                  key: DB_PASSWORD
          # Opsional: Mount volume agar data tidak hilang saat restart (Testing boleh skip)
          # volumeMounts:
          #   - name: db-data
          #     mountPath: /var/lib/postgresql/data
