apiVersion: v1
kind: Secret
metadata:
  name: roomify-secrets
type: Opaque
stringData:
  APP_KEY: "base64:PP55f/+hsfSHatZ249sbVitdGVjlGb8K8JflgM28LZk="
  APP_DEBUG: "true"
  APP_URL: "http://localhost:30080"
  ASSET_URL: "http://localhost:30080"

  DB_CONNECTION: "pgsql"
  # --- BAGIAN INI BERUBAH ---
  # Menggunakan FQDN (Fully Qualified Domain Name)
  DB_HOST: "postgresql-prod.database-prod.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "postgres" # Default database biasanya 'postgres', sesuaikan jika Anda buat DB baru
  DB_USERNAME: "postgres" # Default user
  DB_PASSWORD: "admin123"
  # --------------------------


apiVersion: v1
kind: Secret
metadata:
  name: roomify-secrets
type: Opaque
stringData:
  APP_KEY: "base64:..." # Samakan dengan testing atau generate baru
  APP_DEBUG: "false"    # Production harus FALSE
  APP_ENV: "production" # PENTING: Agar HTTPS force scheme jalan (jika pakai SSL)
  APP_URL: "http://localhost:30081"   # Port beda dengan testing
  ASSET_URL: "http://localhost:30081" # Port beda dengan testing

  DB_CONNECTION: "pgsql"
  # Mengarah ke Database Persistent yang sama
  DB_HOST: "postgres-postgresql.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "postgres" # Bisa ganti nama DB jika ingin data terpisah (create manual dulu)
  DB_USERNAME: "postgres"
  DB_PASSWORD: "admin123"
