apiVersion: v1
kind: Secret
metadata:
  name: roomify-secrets
type: Opaque
stringData:
  APP_KEY: "base64:PP55f/+hsfSHatZ249sbVitdGVjlGb8K8JflgM28LZk="
  APP_DEBUG: "true"
  APP_URL: "http://localhost:30080"
  ASSET_URL: "http://localhost:30080"

  DB_CONNECTION: "pgsql"
  # --- BAGIAN INI BERUBAH ---
  # Menggunakan FQDN (Fully Qualified Domain Name)
  DB_HOST: "postgresql-test.database-test.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "postgres" # Default database biasanya 'postgres', sesuaikan jika Anda buat DB baru
  DB_USERNAME: "postgres" # Default user
  DB_PASSWORD: "admin123"
  # --------------------------
