apiVersion: v1
kind: Secret
metadata:
  name: roomify-secrets
type: Opaque
stringData:
  # GANTI value di bawah ini sesuai kebutuhan
  APP_KEY: "base64:PP55f/+hsfSHatZ249sbVitdGVjlGb8K8JflgM28LZk="
  APP_DEBUG: "true"
  DB_CONNECTION: "pgsql"
  DB_HOST: "roomify-db"  # Harus sama dengan nama Service Database di bawah
  DB_PORT: "5432"
  DB_DATABASE: "roomify"
  DB_USERNAME: "roomify_user"
  DB_PASSWORD: "super_secret_password"
