apiVersion: v1
kind: Secret
metadata:
  name: roomify-secrets
type: Opaque
stringData:
  APP_KEY: "base64:..." # (Sama dengan sebelumnya)
  APP_DEBUG: "false"
  APP_ENV: "production"

  # --- BAGIAN INI YANG SALAH ---
  # Ganti 30080 menjadi 30081
  APP_URL: "http://localhost:30081"
  ASSET_URL: "http://localhost:30081"
  # -----------------------------

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgresql-prod.database-prod.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "postgres"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "admin123"
