apiVersion: v1
kind: Service
metadata:
  name: roomify-service
spec:
  selector:
    app: roomify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Bisa diakses via IP_NODE:30080
  type: NodePort
